### ISSUE TITLE
Support Number Matchers

### ISSUE THREAD

**Issue by ASaiAnudeep** [pactumjs/pactum-matchers#4]
> **pactum-matchers** helps to validate json content in REST API testing.

This issue focuses on adding new matchers to validate numbers.

- `float()` -> numbers with decimals
- `int()` -> numbers without decimals
- `gt(0)` -> greater than given number
- `lt(100)` -> less than given number
- `gte(1)` -> greater than or equal to
- `lte(9)` - > less than or equal to

### AC
- Add the above matchers using this as an example - https://github.com/pactumjs/pactum-matchers/blob/main/src/index.js#L82-L87
- Add tests

**Comment by swaroop9** [comment]
@ASaiAnudeep I would like to work on this issue. Could you please assign it to me.
